### PR TITLE
fix(credentials): Error when getting non existing credentials

### PR DESCRIPTION
**Pull request by pabloperezj**
Fix this [issue](https://github.com/splunk/addonfactory-ucc-library/issues/231).

### CODE REVIEW

**Comment by artemrys** [comment]
@pabloperezj can you please sign the CLA? after that I am happy to merge this PR.

**Comment by pabloperezj** [comment]
recheck

**Comment by pabloperezj** [comment]
> @pabloperezj can you please sign the CLA? after that I am happy to merge this PR.

Done! Thanks!

**Comment by artemrys** [comment]
recheck

**Review by artemrys — APPROVED** [review]

**Pull request merged**
